// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEEmvlBF3xTdgNNrW7qfy5PbUkjTHrC4o',
    appId: '1:40399565067:android:01bc2985caff5d9c61720e',
    messagingSenderId: '40399565067',
    projectId: 'catharsiscards',
    storageBucket: 'catharsiscards.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvjMgWXscMuPNBAmVA7CWn6h40sQ8Ws8o',
    appId: '1:40399565067:ios:997548b9246d604f61720e',
    messagingSenderId: '40399565067',
    projectId: 'catharsiscards',
    storageBucket: 'catharsiscards.firebasestorage.app',
    iosClientId: '40399565067-j4h39bc2ftai8hn3ea2hrmbquafbrm4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.catharsisCards',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9Mq5MksxEiai6cVykz-wEPOw3l0SB0Rc',
    appId: '1:40399565067:web:2a976362c828ecb861720e',
    messagingSenderId: '40399565067',
    projectId: 'catharsiscards',
    authDomain: 'catharsiscards.firebaseapp.com',
    storageBucket: 'catharsiscards.firebasestorage.app',
    measurementId: 'G-MN27X06C3N',
  );

}